### ISSUE TITLE
Vignette not working

### ISSUE THREAD

**Issue by ColeKeenum** [CostaLab/CrossTalkeR#4] opened 2021-03-12 05:05 UTC
Hello, 

Thank you guys for making this package! I think that it will be very helpful.

I ran `vignette('CrossTalkeR')`, but received the following error: 

> Error in Vignette("crosstalker") : could not find function "Vignette"

How can I fix this? I am having other issues with the package, but I think that the vignette would help me understand my problem. I believe that everything else installed normally, as instructed on the homepage of this repository.

**Comment by jsnagai** [comment] 2021-03-12 09:21
Hi @ColeKeenum, thank you for your report.

Would you mind try to install CrossTalkeR again using the command below.

devtools::install_github("https://github.com/CostaLab/CrossTalkeR", build_vignettes = TRUE)

Best

**Comment by ColeKeenum** [comment] 2021-03-12 21:53
@jsnagai thank you. I have tried this, but I am now getting the following error:

> devtools::install_github("https://github.com/CostaLab/CrossTalkeR", build_vignettes = TRUE, force = TRUE)

> Downloading GitHub repo CostaLab/CrossTalkeR@HEAD
> √  checking for file 'C:\Users\colek\AppData\Local\Temp\Rtmpk1TGpL\remotes622410d1bff\CostaLab-CrossTalkeR-e828551/DESCRIPTION' (373ms)
> -  preparing 'CrossTalkeR': (391ms)
> √  checking DESCRIPTION meta-information ... 
> -  installing the package to build vignettes
> E  creating vignettes (8.4s)
>    --- re-building 'CrossTalkeR.Rmd' using rmarkdown
>    Reading Files
>    Warning in gzfile(file, mode) :
>      cannot open compressed file 'C:/Users/colek/Documents/Documents//LR_data.Rds', probable reason 'No such file or directory'
>    Quitting from lines 58-71 (CrossTalkeR.Rmd) 
>    Error: processing vignette 'CrossTalkeR.Rmd' failed with diagnostics:
>    cannot open the connection
>    --- failed re-building 'CrossTalkeR.Rmd'
>    
>    SUMMARY: processing the following file failed:
>      'CrossTalkeR.Rmd'
>    
>    Error: Vignette re-building failed.
>    Execution halted
> Error: Failed to install 'CrossTalkeR' from GitHub:
>   System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> Quitting from lines 58-71 (CrossTalkeR.Rmd) 
> E> Error: processing vignette 'CrossTalkeR.Rmd' failed with diagnostics:
> E> cannot open the connection
> E> --- failed re-building 'CrossTalkeR.Rmd'
> E> 
> E> SUMMARY: processing the following file failed:
> E>   'CrossTalkeR.Rmd'
> E> 
> E> Error: Vignette re-building failed.
> E> Execution halted
> > devtools::install_github("https://github.com/CostaLab/CrossTalkeR", build_vignettes = TRUE)
> Downloading GitHub repo CostaLab/CrossTalkeR@HEAD
> √  checking for file 'C:\Users\colek\AppData\Local\Temp\Rtmpk1TGpL\remotes622454cb50eb\CostaLab-CrossTalkeR-e828551/DESCRIPTION' (389ms)
> -  preparing 'CrossTalkeR': (365ms)
> √  checking DESCRIPTION meta-information ... 
> -  installing the package to build vignettes
> E  creating vignettes (8.9s)
>    --- re-building 'CrossTalkeR.Rmd' using rmarkdown
>    Reading Files
>    Warning in gzfile(file, mode) :
>      cannot open compressed file 'C:/Users/colek/Documents/Documents//LR_data.Rds', probable reason 'No such file or directory'
>    Quitting from lines 58-71 (CrossTalkeR.Rmd) 
>    Error: processing vignette 'CrossTalkeR.Rmd' failed with diagnostics:
>    cannot open the connection
>    --- failed re-building 'CrossTalkeR.Rmd'
>    
>    SUMMARY: processing the following file failed:
>      'CrossTalkeR.Rmd'
>    
>    Error: Vignette re-building failed.
>    Execution halted
> Error: Failed to install 'CrossTalkeR' from GitHub:
>   System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> Quitting from lines 58-71 (CrossTalkeR.Rmd) 
> E> Error: processing vignette 'CrossTalkeR.Rmd' failed with diagnostics:
> E> cannot open the connection
> E> --- failed re-building 'CrossTalkeR.Rmd'
> E> 
> E> SUMMARY: processing the following file failed:
> E>   'CrossTalkeR.Rmd'
> E> 
> E> Error: Vignette re-building failed.
> E> Execution halted

**Comment by jsnagai** [comment] 2021-03-12 22:20
Dear @ColeKeenum ,

I will fix it on the vignettes in the next days. By now, you might be able to run it by creating a folder Documents in your Documents File. 

Again, thank you for reporting the issue.

**Comment by algarji** [comment] 2021-03-25 16:47
I also have the same problem with the vignette. If you don't mind, you can notify  here when the problem is solved so then I can try and better understand the package.

**Comment by jsnagai** [comment] 2021-03-31 08:32
@algarji and @ColeKeenum, Would you mind try the new release of the package? We did several modifications and improvements. Also a git page documentation will be released soon. Thank you for commenting your issues and for using our tool

**Comment by ColeKeenum** [comment] 2021-04-04 00:31
Apologies for the delay, I installed the new release, but received the following error:
```
> vignette('CrossTalkeR')
Warning message:
vignette ‘CrossTalkeR’ not found 
```

**Comment by jsnagai** [comment] 2021-04-13 09:11
Hi @ColeKeenum sorry for the late reply. Did you remembered to set  build_vignettes = TRUE ?

**Comment by ColeKeenum** [comment] 2021-04-18 15:31
@jsnagai It works now. I didn't do the github install. Thanks!

Looking forward to using this soon!

**Comment by jsnagai** [comment] 2021-04-20 17:01
Thank you !! And good luck with you data!!!

**Closed by jsnagai** 2021-04-20 17:01 UTC
Labels: question
